# docker-compose.yml for the microservice
version: '3.8'
services:
  scraper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REDIS_URL=redis://redis:6379
      - INSTAGRAM_CONCURRENCY=2
      - BROWSER_POOL_SIZE=3
      - LOG_LEVEL=info
      - HEALTH_CHECK_ENABLED=true
      - HEALTH_CHECK_BROWSER_TEST=true
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health/ready']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
