name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Wait for Redis
        run: |
          for i in {1..10}; do
            if redis-cli -h localhost ping | grep PONG; then
              echo "Redis is up!"; break;
            fi
            echo "Waiting for Redis..."; sleep 2;
          done
      - name: Install dependencies
        run: bun install
      - name: Run tests
        env:
          REDIS_URL: redis://localhost:6379
        run: bun test
